language: node_js
node_js:
  - '0.10'
script: "make test-ci"
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-kona' ]; then cd .. && eval "mv $currentfolder generator-kona" && cd generator-kona; fi
after_script: "npm install coveralls@2.10.0 && cat ./coverage/lcov.info | coveralls"